# Generated by Django 5.1.4 on 2024-12-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='url',
            name='shortened_url',
        ),
        migrations.AddField(
            model_name='url',
            name='short_code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(),
        ),
    ]
